title: NBS Training Camp 申请管理系统
description: 一个现代化的特训营申请管理系统，支持申请提交和审批流程
author: Zhaoyue Wang
email: zhaoyw@amazon.com

# GitHub Pages 设置
baseurl: ""
url: ""

# 构建设置
markdown: kramdown
highlighter: rouge

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - DEPLOYMENT.md
  - .gitignore
